enum AllUsersActionTypes {
    ALL_USERS_REQUEST_DATA = "ALL_USERS_REQUEST_DATA",
    ALL_USERS_LOAD_DATA = "ALL_USERS_LOAD_DATA",
    ALL_USERS_SELECT_CELL_TO_EDIT = "ALL_USERS_SELECT_CELL_TO_EDIT",
};

export default AllUsersActionTypes;